generator:
  class: sfPropelGenerator
  param:
    model_class:           twSubscriptionTemplate
    theme:                 twadmin15
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          tw_subscription_template
    with_propel_route:     1

    config:
      actions: ~
      fields:
        id: { label: ID }
        type_id: { label: Template type, help: Text emails can have only text inside. }
        type:  { label: Template type }
        t_name: { label: Template name, help: Choose name easy to connect with template. }
        t_data:
          label: Template body
          help: >
            Please put here your template data. To have personalized information you can use special tags like {{email}} or {{fullname}} which are ne change to email adres and Fullname of user who will gain this message. To add special link to unsubscribe from this list please use tag {{unsubscribe}}.
      
      list:
        title: Templates
        display: [t_name, type]
        max_per_page: 10
      
      filter:
        display: [type_id, t_name]
        
      form:    ~
      edit:
        title: > 
          Template: %%t_name%%
          
      new:     ~
