generator:
  class: sfPropelGenerator
  param:
    model_class:           twSubscriptionEmail
    theme:                 admin
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          tw_subscription_email
    with_propel_route:     1

    config:
      actions: ~
      fields:
        list_id: { label: List name }
        listname: { label: List name }
        remail: { label: Recipient email, help: To this email - emails will be sent }
        rname: { label: Recipient name }
        auth_key: { label: Unsubscribe code, help: This record will be automaticly set and must be unique }
        status: { label: Email status }
        status_id: { label: Email status }
      
      list:
        title: Your Emails
        display: [listname, status, remail, rname, created_at]
        max_per_page: 10
        actions:
          _new: ~
          return: { label: powrót do listy }
      
      filter:
        display: [list_id, status_id, remail, rname]
        
      form:    ~
      edit:
        title: > 
          Your Emails: %%remail%%
      new:
        title: Add Email to list
