generator:
  class: sfPropelGenerator
  param:
    model_class:           twSubscriptionMailQueue
    theme:                 twadmin15
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          tw_subscription_mail_queue
    with_propel_route:     1

    config:
      actions: ~
      fields:
        id: { label: ID }
        type_id: { label: Message type }
        subject: { label: Message subject }
        from_address: { label: Email from }
        r_email: { label: Recipient email }
        r_name: { label: Recipient name }
        time_to_send: { label: Time to send }
      
      list:
        title: Emails Queue
        display: [id, message_type, subject, from_address, r_email, r_name, time_to_send, created_at]
        max_per_page: 10
        object_actions:
          _delete: ~
        batch_actions:
          _delete: ~
      
      filter:
        display: [ list_id, type_id, r_email ]
      
      form:    ~
      edit:    ~
      new:     ~
