generator:
  class: sfPropelGenerator
  param:
    model_class:           twSubscriptionMailSent
    theme:                 twadmin15
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          tw_subscription_mail_sent
    with_propel_route:     1

    config:
      actions: ~
      fields:
        id: { label: ID }
        sender: { label: Email from }
        remail: { label: Recipient email }
        time_to_send: { label: Time to send }
      
      list:
        title: Sent Emails
        display: [sender, remail, time_to_send, created_at]
        max_per_page: 10
        object_actions:
          _delete: ~
        batch_actions:
          _delete: ~
      
      filter:
        display: [ remail ]
        
      form:    ~
      edit:    ~
      new:     ~
