generator:
  class: sfPropelGenerator
  param:
    model_class:           twSubscriptionList
    theme:                 twadmin15
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          tw_subscription_list
    with_propel_route:     1

    config:
      actions: ~
      fields:
        id: { label: ID }
        list_name: { label: List name }
        type_id: { label: List type }
        list_type: { label: List type }
        list_desc: { label: List description }
        from_address: { label: Email from }
        smtp_host: { label: SMTP Host }
        smtp_port: { label: SMTP Port }
        smtp_encr: { label: SMTP Encryption }
        smtp_user: { label: SMTP Username }
        smtp_pass: { label: SMTP Password }
        web_base_url: { label: Website base URL }
        sentmail: { help: From this email - emails will be sent }
        template_id: { params: include_custom=-- choose template to connect with list --, help: You can select template to spedup mailing creation }

      list:
        title: Your Lists
        query_methods: [withI18n]
        display: [list_name, list_type, emails, create_mailing]
        max_per_page: 10
        object_actions:
          _code: { label: Code, action: code, params: { class: 'btn btn-small' } }
          _edit: ~
          _delete: ~
        actions:
          _new: ~
        batch_actions:
          _delete: ~

      filter:
        display: [list_name, type_id, template_id]
        
      form:    ~
      edit:
        title: > 
          Your List: %%list_name%%

      new:     ~